#### **Practical List Question 2. Write programs in Python using NumPy library to do the following:**

    a. Compute the mean, standard deviation, and variance of a two dimensional random integer array along the second axis.
    b. Get the indices of the sorted elements of a given array.
             B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
             Hint: Use np.argsort
    c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data type of the array and then reshape it into nx m array, n and m are user inputs given at the run time.
    d. Test whether the elements of a given array are zero, non-zero and NaN. Record the indices of these elements in three separate arrays.


In [ ]:
#a. Compute the mean, standard deviation, and variance of a two dimensional random integer array along the second axis.
import numpy as np
A=np.arange(1,21).reshape(4,5)
x=np.mean(A)
print("Mean: ",x)
y=np.std(A)
print("Standard Deviation: ",y)
z=np.var(A)
print("Variance: ",z)

Mean:  10.5
Standard Deviation:  5.766281297335398
Variance:  33.25


In [ ]:
#b. Get the indices of the sorted elements of a given array.
#   B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
import numpy as np
B=np.array([56, 48, 22, 41, 78, 91, 24, 46, 8, 33])
print("Original array:",B)
A=np.argsort(B)
print("Indices of the sorted elements of original array:")
print(A)

Original array: [56 48 22 41 78 91 24 46  8 33]
Indices of the sorted elements of original array:
[8 2 6 9 3 7 1 0 4 5]


In [ ]:
#c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data type of the array
#   and then reshape it into nx m array, n and m are user inputs given at the run time.
import numpy as np
x=eval(input("Enter the no. of rows:"))
y=eval(input("Enter the no. of columns:"))

A=np.arange(1,31).reshape(x,y)
print("Matrix A:")
print(A)
print("Shape of array:",A.shape)
print("Data type of array:",A.dtype)

A=np.arange(1,31).reshape(y,x)
print("After reshaping:")
print(A)


Enter the no. of rows:5
Enter the no. of columns:6
Matrix A:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Shape of array: (5, 6)
Data type of array: int64
After reshaping:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
#d. Test whether the elements of a given array are zero, non-zero and NaN.
#   Record the indices of these elements in three separate arrays.
import numpy as np
=

#### <font color='green'>**Link to Numpy Documentation:** https://numpy.org/doc/stable/reference/</font>

In [ ]:
### TO DO ###

#### **Practice Questions**

1. Write a program to create an NumPy array of all the even integers from 30 to 70.
2. Write a program to create a 10x10 NumPy matrix, in which the elements on the borders will be equal to 1, and inside 0.
3. Write a program to create a 5x10 NumPy  matrix of distinct numbers from 1 to 50 and swap 2nd and 3rd column in a 2d NumPy array.
4. Write a program to create a 5x10 NumPy  matrix of distinct numbers from 1 to 50 and swap 2nd and 3rd row in a 2d NumPy array.
5. Add the two 2d NumPy arrays and modify the  resulting array by calculating the square root of each element
6. Create a 5X2 NumPy integer array from a range between 100 to 200 such that the difference between each element is 10. Retrive indexes of only those elements where numbers are divisible by 3.


In [ ]:
### TO DO ###

In [ ]:
#Q1 Write a program to create an NumPy array of all the even integers from 30 to 70.
import numpy as np
A=np.arange(30,71,2)
print("Even integers from 30 to 70:",A)


Even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
#Q2 Write a program to create a 10x10 NumPy matrix, in which the elements on the borders will be equal to 1, and inside 0.
import numpy as np
A= np.ones((10, 10))
A[1:-1, 1:-1] = 0
print("Matrix:")
print(A)

Matrix:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#Q3 Write a program to create a 5x10 NumPy matrix of distinct numbers from 1 to 50 and swap 2nd and 3rd column in a 2d NumPy array.
import numpy as np
A=np.arange(1,51).reshape(5,10)
print("Original Matrix:")
print(A)
A[:,[1,2]]=A[:,[2,1]]
print("Modified Matrix:")
print(A)


Original Matrix:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
Modified Matrix:
[[ 1  3  2  4  5  6  7  8  9 10]
 [11 13 12 14 15 16 17 18 19 20]
 [21 23 22 24 25 26 27 28 29 30]
 [31 33 32 34 35 36 37 38 39 40]
 [41 43 42 44 45 46 47 48 49 50]]


In [ ]:
#Q4 Write a program to create a 5x10 NumPy matrix of distinct numbers from 1 to 50 and swap 2nd and 3rd row in a 2d NumPy array.

import numpy as np
A=np.arange(1,51).reshape(5,10)
print("Original Matrix:")
print(A)
A[[1,2]]=A[[2,1]]
print("Modified Matrix:")
print(A)



Original Matrix:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
Modified Matrix:
[[ 1  2  3  4  5  6  7  8  9 10]
 [21 22 23 24 25 26 27 28 29 30]
 [11 12 13 14 15 16 17 18 19 20]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [ ]:
#Q5 Add the two 2d NumPy arrays and modify the resulting array by calculating the square root of each element
import numpy as np
A=np.arange(1,21).reshape(4,5)
B=np.arange(21,41).reshape(4,5)
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
C=np.add(A,B)
print("Sum:")
print(C)
D=np.sqrt(C)
print("Modified matrix:")
print(D)

Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Matrix B:
[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]
Sum:
[[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]]
Modified matrix:
[[4.69041576 4.89897949 5.09901951 5.29150262 5.47722558]
 [5.65685425 5.83095189 6.         6.164414   6.32455532]
 [6.4807407  6.63324958 6.78232998 6.92820323 7.07106781]
 [7.21110255 7.34846923 7.48331477 7.61577311 7.74596669]]


In [ ]:
#Q6 Create a 5X2 NumPy integer array from a range between 100 to 200 such that the difference between each element is 10.
#   Retrive indexes of only those elements where numbers are divisible by 3.

import numpy as np
A=np.arange(100,200,10).reshape(5,2)
print("Matrix A:")
print(A)
print("Elements divisible by 3:",np.argwhere(A%3==0))


Matrix A:
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
Elements divisible by 3: [[1 0]
 [2 1]
 [4 0]]


In [ ]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [ ]:
help(np.max)

Help on function amax in module numpy:

amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Return the maximum of an array or maximum along an axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to operate.  By default, flattened input is
        used.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, the maximum is selected over multiple axes,
        instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternative output array in which to place the result.  Must
        be of the same shape and buffer length as the expected output.
        See `ufuncs-output-type` for more details.
    
    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        the result will